Fix usage of time.sleep
When I extracted the amount of seconds of the sleep timeout between runs
I accidentally forgot to convert the string returned by `environ.get` to
the number `time.sleep` needs. 💩

```
Traceback (most recent call last):
  File "./racbot.py", line 141, in <module>
    scan_new_threads()
  File "./racbot.py", line 85, in scan_new_threads
    time.sleep(SLEEP_TIMEOUT)
TypeError: a float is required
```